"""RTL domain records."""

from dv_platform.domain.models import (
    HDLFile,
    RTLAssignment,
    RTLBranch,
    RTLCDCPath,
    RTLClock,
    RTLConnection,
    RTLControlDomain,
    RTLExpression,
    RTLGenerateScope,
    RTLInstance,
    RTLMemory,
    RTLMemoryAccess,
    RTLModule,
    RTLParameter,
    RTLParameterBinding,
    RTLPort,
    RTLProceduralBlock,
    RTLProceduralPattern,
    RTLProject,
    RTLProperty,
    RTLProtocol,
    RTLReset,
    RTLSemanticFeature,
    RTLType,
    RTLTypeMember,
)

__all__ = [
    "HDLFile",
    "RTLAssignment",
    "RTLBranch",
    "RTLCDCPath",
    "RTLClock",
    "RTLConnection",
    "RTLControlDomain",
    "RTLExpression",
    "RTLGenerateScope",
    "RTLInstance",
    "RTLMemory",
    "RTLMemoryAccess",
    "RTLModule",
    "RTLParameter",
    "RTLParameterBinding",
    "RTLPort",
    "RTLProceduralBlock",
    "RTLProceduralPattern",
    "RTLProject",
    "RTLProperty",
    "RTLProtocol",
    "RTLReset",
    "RTLSemanticFeature",
    "RTLType",
    "RTLTypeMember",
]
