"""Schema compatibility constants that are safe to import during startup."""

RTL_FACTS_SCHEMA_VERSION = 11
MIN_READABLE_RTL_FACTS_SCHEMA_VERSION = 1
PLAN_SCHEMA_VERSION = 18
MIN_READABLE_PLAN_SCHEMA_VERSION = 1

PLAN_REVISION_SCHEMA_VERSION = 3
VALIDATION_RESULT_SCHEMA_VERSION = 1
