"""Schema compatibility constants that are safe to import during startup."""

RTL_FACTS_SCHEMA_VERSION = 9
MIN_READABLE_RTL_FACTS_SCHEMA_VERSION = 1
PLAN_SCHEMA_VERSION = 17
MIN_READABLE_PLAN_SCHEMA_VERSION = 1

PLAN_REVISION_SCHEMA_VERSION = 2
VALIDATION_RESULT_SCHEMA_VERSION = 1
