"""Agentic RTL verification generation platform."""

__version__ = "0.1.0"

from dv_platform.agent.contracts import AgentProposal, AgentRun, AgentTask, FeedbackEvent, PlanRevision, SkillDescriptor
from dv_platform.agent.protocols import (
    ProtocolProfile,
    ProtocolSignal,
    production_protocol_profiles,
    protocol_profile,
    protocol_profile_from_json,
    protocol_profile_to_json,
)
from dv_platform.core.models import (
    ArtifactKind,
    ArtifactQualityRequirement,
    ClaimStatus,
    CLIConfig,
    DesignDecision,
    DocumentationChunk,
    EvidenceKind,
    EvidenceRef,
    FormalToolConfig,
    GeneratedArtifact,
    HDLFile,
    RTLExpression,
    RTLModule,
    RTLPort,
    RTLProject,
    RTLProtocol,
    Severity,
    SimulatorConfig,
    VerificationBehavior,
    VerificationClaim,
    VerificationPlan,
    VerificationRequirement,
    VerificationTarget,
)

__all__ = [
    "__version__",
    "ArtifactKind",
    "ArtifactQualityRequirement",
    "CLIConfig",
    "ClaimStatus",
    "DesignDecision",
    "DocumentationChunk",
    "EvidenceKind",
    "EvidenceRef",
    "FormalToolConfig",
    "GeneratedArtifact",
    "HDLFile",
    "RTLModule",
    "RTLPort",
    "RTLProject",
    "Severity",
    "SimulatorConfig",
    "VerificationBehavior",
    "VerificationClaim",
    "VerificationPlan",
    "VerificationRequirement",
    "VerificationTarget",
    "RTLExpression",
    "RTLProtocol",
    "AgentProposal",
    "AgentRun",
    "AgentTask",
    "FeedbackEvent",
    "PlanRevision",
    "SkillDescriptor",
    "ProtocolProfile",
    "ProtocolSignal",
    "production_protocol_profiles",
    "protocol_profile",
    "protocol_profile_from_json",
    "protocol_profile_to_json",
]
